#!/usr/bin/env bash

SCRIPT_PATH="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

source "$(dirname "$SCRIPT_DIR")/envs/paths.env"
source "$(dirname "$SCRIPT_DIR")/envs/secrets.env"

rm -rf "$SCRIPT_DIR/builds"
mkdir "$SCRIPT_DIR/builds"

echo
echo "Starting Unity build..."

# -logFile - \
# -stackTraceLogType Full 
# -verbose 

"$UNITY_PATH" \
  -batchmode -quit \
  -projectPath "$PROJECT_PATH_ANDROID" \
  -executeMethod AndroidBuildCommand.BuildAndroidApp \
  buildPath="$SCRIPT_DIR/builds/app.apk" \
  KeystoreName="$KeystoreName" \
  KeystorePass="$KeystorePass" \
  KeyaliasName="$KeyaliasName" \
  KeyaliasPass="$KeyaliasPass" \

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "Unity build failed with exit code $EXIT_CODE."
  exit 1
else
  echo "Unity build completed."
  exit 0
fi
