#!/usr/bin/env bash

SCRIPT_PATH="$(realpath "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"

source "$(dirname "$SCRIPT_DIR")/envs/paths.env"

rm -rf "$SCRIPT_DIR/builds"
mkdir "$SCRIPT_DIR/builds"

echo
echo "Starting Unity build..."

"$UNITY_PATH" \
  -batchmode -quit \
  -projectPath "$PROJECT_PATH_MACOS" \
  -executeMethod MacOSServerBuildCommand.BuildMacServer \
  buildPath="$SCRIPT_DIR/builds/server_app" \

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "Unity build failed with exit code $EXIT_CODE."
  exit 1
else
  echo "Unity build completed."
  exit 0
fi
